export const stateOptions = [
  { key: "1", text: "Alabama", value: "AL" },
  { key: "2", text: "Alaska", value: "AK" },
  { key: "4", text: "Arizona", value: "AZ" },
  { key: "5", text: "Arkansas", value: "AR" },
  { key: "6", text: "California", value: "CA" },
  { key: "7", text: "Colorado", value: "CO" },
  { key: "8", text: "Connecticut", value: "CT" },
  { key: "9", text: "Delaware", value: "DE" },
  { key: "10", text: "Florida", value: "FL" },
  { key: "11", text: "Georgia", value: "GA" },
  { key: "13", text: "Hawaii", value: "HI" },
  { key: "14", text: "Idaho", value: "ID" },
  { key: "15", text: "Illinois", value: "IL" },
  { key: "16", text: "Indiana", value: "IN" },
  { key: "17", text: "Iowa", value: "IA" },
  { key: "18", text: "Kansas", value: "KS" },
  { key: "19", text: "Kentucky", value: "KY" },
  { key: "20", text: "Louisiana", value: "LA" },
  { key: "21", text: "Maine", value: "ME" },
  { key: "22", text: "Maryland", value: "MD" },
  { key: "23", text: "Massachusetts", value: "MA" },
  { key: "24", text: "Michigan", value: "MI" },
  { key: "25", text: "Minnesota", value: "MN" },
  { key: "26", text: "Mississippi", value: "MS" },
  { key: "27", text: "Missouri", value: "MO" },
  { key: "28", text: "Montana", value: "MT" },
  { key: "29", text: "Nebraska", value: "NE" },
  { key: "30", text: "Nevada", value: "NV" },
  { key: "31", text: "New Hampshire", value: "NH" },
  { key: "32", text: "New Jersey", value: "NJ" },
  { key: "33", text: "New Mexico", value: "NM" },
  { key: "34", text: "New York", value: "NY" },
  { key: "35", text: "North Carolina", value: "NC" },
  { key: "36", text: "North Dakota", value: "ND" },
  { key: "37", text: "Ohio", value: "OH" },
  { key: "38", text: "Oklahoma", value: "OK" },
  { key: "39", text: "Oregon", value: "OR" },
  { key: "41", text: "Pennsylvania", value: "PA" },
  { key: "42", text: "Puerto Rico", value: "PR" },
  { key: "43", text: "Rhone Island", value: "RI" },
  { key: "44", text: "South Carolina", value: "SC" },
  { key: "45", text: "Soth Dakota", value: "SD" },
  { key: "46", text: "Tennessee", value: "TN" },
  { key: "47", text: "Texas", value: "TX" },
  { key: "48", text: "Utah", value: "UT" },
  { key: "49", text: "Vermont", value: "VT" },
  { key: "50", text: "Virgin Islands", value: "VI" },
  { key: "51", text: "Virginia", value: "VA" },
  { key: "52", text: "Washington", value: "WA" },
  { key: "53", text: "West Virginia", value: "WV" },
  { key: "54", text: "Wisconson", value: "WI" },
  { key: "55", text: "Wyoming", value: "WY" }
];
